#!/usr/bin/env bash
# Helper to create a named Cloudflare Tunnel and write a config.yml
# Usage: ./named-tunnel-setup.sh
# Requirements: cloudflared installed and `cloudflared tunnel login` already completed

set -euo pipefail

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Install it first: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation"
  exit 2
fi

TUNNEL_NAME="my-schedule-tunnel"
read -p "Tunnel name (default: ${TUNNEL_NAME}): " input
TUNNEL_NAME=${input:-$TUNNEL_NAME}

read -p "Hostname to route (e.g. schedule.example.com) [leave empty to skip DNS routing]: " HOSTNAME

echo "\nCreating tunnel '${TUNNEL_NAME}'..."
# Create tunnel (requires cloudflared login / Cloudflare account)
TUNNEL_CREATE_OUTPUT=$(cloudflared tunnel create "${TUNNEL_NAME}" 2>&1 || true)
if echo "$TUNNEL_CREATE_OUTPUT" | grep -q 'Created tunnel'; then
  echo "$TUNNEL_CREATE_OUTPUT"
else
  echo "cloudflared tunnel create output:\n$TUNNEL_CREATE_OUTPUT"
  echo "If tunnel already exists, try: cloudflared tunnel list"
fi

# Try to detect tunnel UUID from credentials file
CREDS_DIR=~/.cloudflared
UUID=""
for f in "$CREDS_DIR"/*.json; do
  if [ -f "$f" ]; then
    # read uuid from filename
    bn=$(basename "$f")
    if [[ "$bn" == *"${TUNNEL_NAME}"* ]] || true; then
      UUID=$(echo "$bn" | sed -E 's/\.json$//')
      # prefer exact match: cloudflared names file as <UUID>.json so try parse file content
      if [ -n "$UUID" ]; then break; fi
    fi
  fi
done

if [ -z "$UUID" ]; then
  echo "Could not automatically determine tunnel UUID. List tunnels with:\n  cloudflared tunnel list\nand set UUID manually." >&2
  echo "Setup aborted." >&2
  exit 1
fi

CONFIG_DIR=~/.cloudflared
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yml"

echo "Writing config to $CONFIG_FILE"
cat > "$CONFIG_FILE" <<EOF
# Generated by named-tunnel-setup.sh
# Tunnel: ${TUNNEL_NAME}
# Do not commit your credentials file to source control.
tunnel: ${UUID}
credentials-file: ${CONFIG_DIR}/${UUID}.json
ingress:
  - hostname: ${HOSTNAME:-example.local}
    service: http://127.0.0.1:3000
  - service: http_status:404
EOF

echo "Config written."

if [ -n "$HOSTNAME" ]; then
  echo "Attempting to create DNS CNAME for ${HOSTNAME} to tunnel (requires Cloudflare account & access)..."
  echo "Running: cloudflared tunnel route dns ${TUNNEL_NAME} ${HOSTNAME}"
  cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" || echo "Failed to create DNS route. Please create DNS record in Cloudflare dashboard or run the command manually."
fi

echo "To run the tunnel:"
echo "  cloudflared tunnel run ${TUNNEL_NAME}"

echo "Done."
